# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy

  - repo: git@github.com:astral-sh/ruff-pre-commit.git
    rev: v0.0.241
    hooks:
      - id: ruff
        args: ["check"]
        stages: ["push"]
