version: '3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.10-bookworm
    volumes:
      - .:/workspace:cached
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

  test:
    image: mcr.microsoft.com/devcontainers/python:1-3.10-bookworm
    volumes:
      - .:/workspace:cached
    build:
      context: .
      dockerfile: Dockerfile_test

